kiss_icp_node:
  ros__parameters:
    pointcloud_topic: "/velodyne_points"
    publish_odom_tf: false
    visualize: false

    # KISS-ICP specific parameters
    max_range: 60.0
    min_range: 2.0
    deskew: true
    voxel_size: 0.1
    max_points_per_voxel: 20
    initial_threshold: 2.0
    min_motion_th: 0.1
